
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

/******************************************************************

DO NOT MODIFY. AUTOGENERATED FILE.
This file is generated using the logic from <root>/src/scripts/genEventing.py

******************************************************************/

BOOL EventPipeEventEnabledGCStart();
ULONG EventPipeWriteEventGCStart(
    const unsigned int  Count,
    const unsigned int  Reason
);
BOOL EventPipeEventEnabledGCStart_V1();
ULONG EventPipeWriteEventGCStart_V1(
    const unsigned int  Count,
    const unsigned int  Depth,
    const unsigned int  Reason,
    const unsigned int  Type,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCStart_V2();
ULONG EventPipeWriteEventGCStart_V2(
    const unsigned int  Count,
    const unsigned int  Depth,
    const unsigned int  Reason,
    const unsigned int  Type,
    const unsigned short  ClrInstanceID,
    const unsigned __int64  ClientSequenceNumber
);
BOOL EventPipeEventEnabledGCEnd();
ULONG EventPipeWriteEventGCEnd(
    const unsigned int  Count,
    const unsigned short  Depth
);
BOOL EventPipeEventEnabledGCEnd_V1();
ULONG EventPipeWriteEventGCEnd_V1(
    const unsigned int  Count,
    const unsigned int  Depth,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCRestartEEEnd();
ULONG EventPipeWriteEventGCRestartEEEnd(

);
BOOL EventPipeEventEnabledGCRestartEEEnd_V1();
ULONG EventPipeWriteEventGCRestartEEEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCHeapStats();
ULONG EventPipeWriteEventGCHeapStats(
    const unsigned __int64  GenerationSize0,
    const unsigned __int64  TotalPromotedSize0,
    const unsigned __int64  GenerationSize1,
    const unsigned __int64  TotalPromotedSize1,
    const unsigned __int64  GenerationSize2,
    const unsigned __int64  TotalPromotedSize2,
    const unsigned __int64  GenerationSize3,
    const unsigned __int64  TotalPromotedSize3,
    const unsigned __int64  FinalizationPromotedSize,
    const unsigned __int64  FinalizationPromotedCount,
    const unsigned int  PinnedObjectCount,
    const unsigned int  SinkBlockCount,
    const unsigned int  GCHandleCount
);
BOOL EventPipeEventEnabledGCHeapStats_V1();
ULONG EventPipeWriteEventGCHeapStats_V1(
    const unsigned __int64  GenerationSize0,
    const unsigned __int64  TotalPromotedSize0,
    const unsigned __int64  GenerationSize1,
    const unsigned __int64  TotalPromotedSize1,
    const unsigned __int64  GenerationSize2,
    const unsigned __int64  TotalPromotedSize2,
    const unsigned __int64  GenerationSize3,
    const unsigned __int64  TotalPromotedSize3,
    const unsigned __int64  FinalizationPromotedSize,
    const unsigned __int64  FinalizationPromotedCount,
    const unsigned int  PinnedObjectCount,
    const unsigned int  SinkBlockCount,
    const unsigned int  GCHandleCount,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCCreateSegment();
ULONG EventPipeWriteEventGCCreateSegment(
    const unsigned __int64  Address,
    const unsigned __int64  Size,
    const unsigned int  Type
);
BOOL EventPipeEventEnabledGCCreateSegment_V1();
ULONG EventPipeWriteEventGCCreateSegment_V1(
    const unsigned __int64  Address,
    const unsigned __int64  Size,
    const unsigned int  Type,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCFreeSegment();
ULONG EventPipeWriteEventGCFreeSegment(
    const unsigned __int64  Address
);
BOOL EventPipeEventEnabledGCFreeSegment_V1();
ULONG EventPipeWriteEventGCFreeSegment_V1(
    const unsigned __int64  Address,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCRestartEEBegin();
ULONG EventPipeWriteEventGCRestartEEBegin(

);
BOOL EventPipeEventEnabledGCRestartEEBegin_V1();
ULONG EventPipeWriteEventGCRestartEEBegin_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCSuspendEEEnd();
ULONG EventPipeWriteEventGCSuspendEEEnd(

);
BOOL EventPipeEventEnabledGCSuspendEEEnd_V1();
ULONG EventPipeWriteEventGCSuspendEEEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCSuspendEEBegin();
ULONG EventPipeWriteEventGCSuspendEEBegin(
    const unsigned short  Reason
);
BOOL EventPipeEventEnabledGCSuspendEEBegin_V1();
ULONG EventPipeWriteEventGCSuspendEEBegin_V1(
    const unsigned int  Reason,
    const unsigned int  Count,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCAllocationTick();
ULONG EventPipeWriteEventGCAllocationTick(
    const unsigned int  AllocationAmount,
    const unsigned int  AllocationKind
);
BOOL EventPipeEventEnabledGCAllocationTick_V1();
ULONG EventPipeWriteEventGCAllocationTick_V1(
    const unsigned int  AllocationAmount,
    const unsigned int  AllocationKind,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCAllocationTick_V2();
ULONG EventPipeWriteEventGCAllocationTick_V2(
    const unsigned int  AllocationAmount,
    const unsigned int  AllocationKind,
    const unsigned short  ClrInstanceID,
    const unsigned __int64  AllocationAmount64,
    const void*  TypeID,
    PCWSTR  TypeName,
    const unsigned int  HeapIndex
);
BOOL EventPipeEventEnabledGCAllocationTick_V3();
ULONG EventPipeWriteEventGCAllocationTick_V3(
    const unsigned int  AllocationAmount,
    const unsigned int  AllocationKind,
    const unsigned short  ClrInstanceID,
    const unsigned __int64  AllocationAmount64,
    const void*  TypeID,
    PCWSTR  TypeName,
    const unsigned int  HeapIndex,
    const void*  Address
);
BOOL EventPipeEventEnabledGCCreateConcurrentThread();
ULONG EventPipeWriteEventGCCreateConcurrentThread(

);
BOOL EventPipeEventEnabledGCCreateConcurrentThread_V1();
ULONG EventPipeWriteEventGCCreateConcurrentThread_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCTerminateConcurrentThread();
ULONG EventPipeWriteEventGCTerminateConcurrentThread(

);
BOOL EventPipeEventEnabledGCTerminateConcurrentThread_V1();
ULONG EventPipeWriteEventGCTerminateConcurrentThread_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCFinalizersEnd();
ULONG EventPipeWriteEventGCFinalizersEnd(
    const unsigned int  Count
);
BOOL EventPipeEventEnabledGCFinalizersEnd_V1();
ULONG EventPipeWriteEventGCFinalizersEnd_V1(
    const unsigned int  Count,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCFinalizersBegin();
ULONG EventPipeWriteEventGCFinalizersBegin(

);
BOOL EventPipeEventEnabledGCFinalizersBegin_V1();
ULONG EventPipeWriteEventGCFinalizersBegin_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBulkType();
ULONG EventPipeWriteEventBulkType(
    const unsigned int  Count,
    const unsigned short  ClrInstanceID,
    int Values_ElementSize,
    const void* Values
);
BOOL EventPipeEventEnabledGCBulkRootEdge();
ULONG EventPipeWriteEventGCBulkRootEdge(
    const unsigned int  Index,
    const unsigned int  Count,
    const unsigned short  ClrInstanceID,
    int Values_ElementSize,
    const void* Values
);
BOOL EventPipeEventEnabledGCBulkRootConditionalWeakTableElementEdge();
ULONG EventPipeWriteEventGCBulkRootConditionalWeakTableElementEdge(
    const unsigned int  Index,
    const unsigned int  Count,
    const unsigned short  ClrInstanceID,
    int Values_ElementSize,
    const void* Values
);
BOOL EventPipeEventEnabledGCBulkNode();
ULONG EventPipeWriteEventGCBulkNode(
    const unsigned int  Index,
    const unsigned int  Count,
    const unsigned short  ClrInstanceID,
    int Values_ElementSize,
    const void* Values
);
BOOL EventPipeEventEnabledGCBulkEdge();
ULONG EventPipeWriteEventGCBulkEdge(
    const unsigned int  Index,
    const unsigned int  Count,
    const unsigned short  ClrInstanceID,
    int Values_ElementSize,
    const void* Values
);
BOOL EventPipeEventEnabledGCSampledObjectAllocationHigh();
ULONG EventPipeWriteEventGCSampledObjectAllocationHigh(
    const void*  Address,
    const void*  TypeID,
    const unsigned int  ObjectCountForTypeSample,
    const unsigned __int64  TotalSizeForTypeSample,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCBulkSurvivingObjectRanges();
ULONG EventPipeWriteEventGCBulkSurvivingObjectRanges(
    const unsigned int  Index,
    const unsigned int  Count,
    const unsigned short  ClrInstanceID,
    int Values_ElementSize,
    const void* Values
);
BOOL EventPipeEventEnabledGCBulkMovedObjectRanges();
ULONG EventPipeWriteEventGCBulkMovedObjectRanges(
    const unsigned int  Index,
    const unsigned int  Count,
    const unsigned short  ClrInstanceID,
    int Values_ElementSize,
    const void* Values
);
BOOL EventPipeEventEnabledGCGenerationRange();
ULONG EventPipeWriteEventGCGenerationRange(
    const unsigned char  Generation,
    const void*  RangeStart,
    const unsigned __int64  RangeUsedLength,
    const unsigned __int64  RangeReservedLength,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCMarkStackRoots();
ULONG EventPipeWriteEventGCMarkStackRoots(
    const unsigned int  HeapNum,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCMarkFinalizeQueueRoots();
ULONG EventPipeWriteEventGCMarkFinalizeQueueRoots(
    const unsigned int  HeapNum,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCMarkHandles();
ULONG EventPipeWriteEventGCMarkHandles(
    const unsigned int  HeapNum,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCMarkOlderGenerationRoots();
ULONG EventPipeWriteEventGCMarkOlderGenerationRoots(
    const unsigned int  HeapNum,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledFinalizeObject();
ULONG EventPipeWriteEventFinalizeObject(
    const void*  TypeID,
    const void*  ObjectID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledSetGCHandle();
ULONG EventPipeWriteEventSetGCHandle(
    const void*  HandleID,
    const void*  ObjectID,
    const unsigned int  Kind,
    const unsigned int  Generation,
    const unsigned __int64  AppDomainID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledDestroyGCHandle();
ULONG EventPipeWriteEventDestroyGCHandle(
    const void*  HandleID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCSampledObjectAllocationLow();
ULONG EventPipeWriteEventGCSampledObjectAllocationLow(
    const void*  Address,
    const void*  TypeID,
    const unsigned int  ObjectCountForTypeSample,
    const unsigned __int64  TotalSizeForTypeSample,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledPinObjectAtGCTime();
ULONG EventPipeWriteEventPinObjectAtGCTime(
    const void*  HandleID,
    const void*  ObjectID,
    const unsigned __int64  ObjectSize,
    PCWSTR  TypeName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCTriggered();
ULONG EventPipeWriteEventGCTriggered(
    const unsigned int  Reason,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCBulkRootCCW();
ULONG EventPipeWriteEventGCBulkRootCCW(
    const unsigned int  Count,
    const unsigned short  ClrInstanceID,
    int Values_ElementSize,
    const void* Values
);
BOOL EventPipeEventEnabledGCBulkRCW();
ULONG EventPipeWriteEventGCBulkRCW(
    const unsigned int  Count,
    const unsigned short  ClrInstanceID,
    int Values_ElementSize,
    const void* Values
);
BOOL EventPipeEventEnabledGCBulkRootStaticVar();
ULONG EventPipeWriteEventGCBulkRootStaticVar(
    const unsigned int  Count,
    const unsigned __int64  AppDomainID,
    const unsigned short  ClrInstanceID,
    int Values_ElementSize,
    const void* Values
);
BOOL EventPipeEventEnabledGCDynamicEvent();
ULONG EventPipeWriteEventGCDynamicEvent(
    PCWSTR  Name,
    const unsigned int  DataSize,
    const BYTE* Data,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledWorkerThreadCreate();
ULONG EventPipeWriteEventWorkerThreadCreate(
    const unsigned int  WorkerThreadCount,
    const unsigned int  RetiredWorkerThreads
);
BOOL EventPipeEventEnabledWorkerThreadTerminate();
ULONG EventPipeWriteEventWorkerThreadTerminate(
    const unsigned int  WorkerThreadCount,
    const unsigned int  RetiredWorkerThreads
);
BOOL EventPipeEventEnabledWorkerThreadRetire();
ULONG EventPipeWriteEventWorkerThreadRetire(
    const unsigned int  WorkerThreadCount,
    const unsigned int  RetiredWorkerThreads
);
BOOL EventPipeEventEnabledWorkerThreadUnretire();
ULONG EventPipeWriteEventWorkerThreadUnretire(
    const unsigned int  WorkerThreadCount,
    const unsigned int  RetiredWorkerThreads
);
BOOL EventPipeEventEnabledIOThreadCreate();
ULONG EventPipeWriteEventIOThreadCreate(
    const unsigned int  IOThreadCount,
    const unsigned int  RetiredIOThreads
);
BOOL EventPipeEventEnabledIOThreadCreate_V1();
ULONG EventPipeWriteEventIOThreadCreate_V1(
    const unsigned int  IOThreadCount,
    const unsigned int  RetiredIOThreads,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledIOThreadTerminate();
ULONG EventPipeWriteEventIOThreadTerminate(
    const unsigned int  IOThreadCount,
    const unsigned int  RetiredIOThreads
);
BOOL EventPipeEventEnabledIOThreadTerminate_V1();
ULONG EventPipeWriteEventIOThreadTerminate_V1(
    const unsigned int  IOThreadCount,
    const unsigned int  RetiredIOThreads,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledIOThreadRetire();
ULONG EventPipeWriteEventIOThreadRetire(
    const unsigned int  IOThreadCount,
    const unsigned int  RetiredIOThreads
);
BOOL EventPipeEventEnabledIOThreadRetire_V1();
ULONG EventPipeWriteEventIOThreadRetire_V1(
    const unsigned int  IOThreadCount,
    const unsigned int  RetiredIOThreads,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledIOThreadUnretire();
ULONG EventPipeWriteEventIOThreadUnretire(
    const unsigned int  IOThreadCount,
    const unsigned int  RetiredIOThreads
);
BOOL EventPipeEventEnabledIOThreadUnretire_V1();
ULONG EventPipeWriteEventIOThreadUnretire_V1(
    const unsigned int  IOThreadCount,
    const unsigned int  RetiredIOThreads,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadpoolSuspensionSuspendThread();
ULONG EventPipeWriteEventThreadpoolSuspensionSuspendThread(
    const unsigned int  ClrThreadID,
    const unsigned int  CpuUtilization
);
BOOL EventPipeEventEnabledThreadpoolSuspensionResumeThread();
ULONG EventPipeWriteEventThreadpoolSuspensionResumeThread(
    const unsigned int  ClrThreadID,
    const unsigned int  CpuUtilization
);
BOOL EventPipeEventEnabledThreadPoolWorkerThreadStart();
ULONG EventPipeWriteEventThreadPoolWorkerThreadStart(
    const unsigned int  ActiveWorkerThreadCount,
    const unsigned int  RetiredWorkerThreadCount,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadPoolWorkerThreadStop();
ULONG EventPipeWriteEventThreadPoolWorkerThreadStop(
    const unsigned int  ActiveWorkerThreadCount,
    const unsigned int  RetiredWorkerThreadCount,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadPoolWorkerThreadRetirementStart();
ULONG EventPipeWriteEventThreadPoolWorkerThreadRetirementStart(
    const unsigned int  ActiveWorkerThreadCount,
    const unsigned int  RetiredWorkerThreadCount,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadPoolWorkerThreadRetirementStop();
ULONG EventPipeWriteEventThreadPoolWorkerThreadRetirementStop(
    const unsigned int  ActiveWorkerThreadCount,
    const unsigned int  RetiredWorkerThreadCount,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadPoolWorkerThreadAdjustmentSample();
ULONG EventPipeWriteEventThreadPoolWorkerThreadAdjustmentSample(
    const double  Throughput,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadPoolWorkerThreadAdjustmentAdjustment();
ULONG EventPipeWriteEventThreadPoolWorkerThreadAdjustmentAdjustment(
    const double  AverageThroughput,
    const unsigned int  NewWorkerThreadCount,
    const unsigned int  Reason,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadPoolWorkerThreadAdjustmentStats();
ULONG EventPipeWriteEventThreadPoolWorkerThreadAdjustmentStats(
    const double  Duration,
    const double  Throughput,
    const double  ThreadWave,
    const double  ThroughputWave,
    const double  ThroughputErrorEstimate,
    const double  AverageThroughputErrorEstimate,
    const double  ThroughputRatio,
    const double  Confidence,
    const double  NewControlSetting,
    const unsigned short  NewThreadWaveMagnitude,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadPoolWorkerThreadWait();
ULONG EventPipeWriteEventThreadPoolWorkerThreadWait(
    const unsigned int  ActiveWorkerThreadCount,
    const unsigned int  RetiredWorkerThreadCount,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadPoolWorkingThreadCount();
ULONG EventPipeWriteEventThreadPoolWorkingThreadCount(
    const unsigned int  Count,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadPoolEnqueue();
ULONG EventPipeWriteEventThreadPoolEnqueue(
    const void*  WorkID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadPoolDequeue();
ULONG EventPipeWriteEventThreadPoolDequeue(
    const void*  WorkID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadPoolIOEnqueue();
ULONG EventPipeWriteEventThreadPoolIOEnqueue(
    const void*  NativeOverlapped,
    const void*  Overlapped,
    const BOOL  MultiDequeues,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadPoolIODequeue();
ULONG EventPipeWriteEventThreadPoolIODequeue(
    const void*  NativeOverlapped,
    const void*  Overlapped,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadPoolIOPack();
ULONG EventPipeWriteEventThreadPoolIOPack(
    const void*  NativeOverlapped,
    const void*  Overlapped,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadCreating();
ULONG EventPipeWriteEventThreadCreating(
    const void*  ID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadRunning();
ULONG EventPipeWriteEventThreadRunning(
    const void*  ID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledExceptionThrown();
ULONG EventPipeWriteEventExceptionThrown(

);
BOOL EventPipeEventEnabledExceptionThrown_V1();
ULONG EventPipeWriteEventExceptionThrown_V1(
    PCWSTR  ExceptionType,
    PCWSTR  ExceptionMessage,
    const void*  ExceptionEIP,
    const unsigned int  ExceptionHRESULT,
    const unsigned short  ExceptionFlags,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledExceptionCatchStart();
ULONG EventPipeWriteEventExceptionCatchStart(
    const unsigned __int64  EntryEIP,
    const unsigned __int64  MethodID,
    PCWSTR  MethodName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledExceptionCatchStop();
ULONG EventPipeWriteEventExceptionCatchStop(

);
BOOL EventPipeEventEnabledExceptionFinallyStart();
ULONG EventPipeWriteEventExceptionFinallyStart(
    const unsigned __int64  EntryEIP,
    const unsigned __int64  MethodID,
    PCWSTR  MethodName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledExceptionFinallyStop();
ULONG EventPipeWriteEventExceptionFinallyStop(

);
BOOL EventPipeEventEnabledExceptionFilterStart();
ULONG EventPipeWriteEventExceptionFilterStart(
    const unsigned __int64  EntryEIP,
    const unsigned __int64  MethodID,
    PCWSTR  MethodName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledExceptionFilterStop();
ULONG EventPipeWriteEventExceptionFilterStop(

);
BOOL EventPipeEventEnabledExceptionThrownStop();
ULONG EventPipeWriteEventExceptionThrownStop(

);
BOOL EventPipeEventEnabledContention();
ULONG EventPipeWriteEventContention(

);
BOOL EventPipeEventEnabledContentionStart_V1();
ULONG EventPipeWriteEventContentionStart_V1(
    const unsigned char  ContentionFlags,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledContentionStop();
ULONG EventPipeWriteEventContentionStop(
    const unsigned char  ContentionFlags,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledCLRStackWalk();
ULONG EventPipeWriteEventCLRStackWalk(
    const unsigned short  ClrInstanceID,
    const unsigned char  Reserved1,
    const unsigned char  Reserved2,
    const unsigned int  FrameCount,
    const void** Stack
);
BOOL EventPipeEventEnabledAppDomainMemAllocated();
ULONG EventPipeWriteEventAppDomainMemAllocated(
    const unsigned __int64  AppDomainID,
    const unsigned __int64  Allocated,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledAppDomainMemSurvived();
ULONG EventPipeWriteEventAppDomainMemSurvived(
    const unsigned __int64  AppDomainID,
    const unsigned __int64  Survived,
    const unsigned __int64  ProcessSurvived,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadCreated();
ULONG EventPipeWriteEventThreadCreated(
    const unsigned __int64  ManagedThreadID,
    const unsigned __int64  AppDomainID,
    const unsigned int  Flags,
    const unsigned int  ManagedThreadIndex,
    const unsigned int  OSThreadID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadTerminated();
ULONG EventPipeWriteEventThreadTerminated(
    const unsigned __int64  ManagedThreadID,
    const unsigned __int64  AppDomainID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadDomainEnter();
ULONG EventPipeWriteEventThreadDomainEnter(
    const unsigned __int64  ManagedThreadID,
    const unsigned __int64  AppDomainID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledILStubGenerated();
ULONG EventPipeWriteEventILStubGenerated(
    const unsigned short  ClrInstanceID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  StubMethodID,
    const unsigned int  StubFlags,
    const unsigned int  ManagedInteropMethodToken,
    PCWSTR  ManagedInteropMethodNamespace,
    PCWSTR  ManagedInteropMethodName,
    PCWSTR  ManagedInteropMethodSignature,
    PCWSTR  NativeMethodSignature,
    PCWSTR  StubMethodSignature,
    PCWSTR  StubMethodILCode
);
BOOL EventPipeEventEnabledILStubCacheHit();
ULONG EventPipeWriteEventILStubCacheHit(
    const unsigned short  ClrInstanceID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  StubMethodID,
    const unsigned int  ManagedInteropMethodToken,
    PCWSTR  ManagedInteropMethodNamespace,
    PCWSTR  ManagedInteropMethodName,
    PCWSTR  ManagedInteropMethodSignature
);
BOOL EventPipeEventEnabledDCStartCompleteV2();
ULONG EventPipeWriteEventDCStartCompleteV2(

);
BOOL EventPipeEventEnabledDCEndCompleteV2();
ULONG EventPipeWriteEventDCEndCompleteV2(

);
BOOL EventPipeEventEnabledMethodDCStartV2();
ULONG EventPipeWriteEventMethodDCStartV2(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags
);
BOOL EventPipeEventEnabledMethodDCEndV2();
ULONG EventPipeWriteEventMethodDCEndV2(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags
);
BOOL EventPipeEventEnabledMethodDCStartVerboseV2();
ULONG EventPipeWriteEventMethodDCStartVerboseV2(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    PCWSTR  MethodNamespace,
    PCWSTR  MethodName,
    PCWSTR  MethodSignature
);
BOOL EventPipeEventEnabledMethodDCEndVerboseV2();
ULONG EventPipeWriteEventMethodDCEndVerboseV2(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    PCWSTR  MethodNamespace,
    PCWSTR  MethodName,
    PCWSTR  MethodSignature
);
BOOL EventPipeEventEnabledMethodLoad();
ULONG EventPipeWriteEventMethodLoad(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags
);
BOOL EventPipeEventEnabledMethodLoad_V1();
ULONG EventPipeWriteEventMethodLoad_V1(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodLoad_V2();
ULONG EventPipeWriteEventMethodLoad_V2(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    const unsigned short  ClrInstanceID,
    const unsigned __int64  ReJITID
);
BOOL EventPipeEventEnabledMethodUnload();
ULONG EventPipeWriteEventMethodUnload(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags
);
BOOL EventPipeEventEnabledMethodUnload_V1();
ULONG EventPipeWriteEventMethodUnload_V1(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodUnload_V2();
ULONG EventPipeWriteEventMethodUnload_V2(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    const unsigned short  ClrInstanceID,
    const unsigned __int64  ReJITID
);
BOOL EventPipeEventEnabledMethodLoadVerbose();
ULONG EventPipeWriteEventMethodLoadVerbose(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    PCWSTR  MethodNamespace,
    PCWSTR  MethodName,
    PCWSTR  MethodSignature
);
BOOL EventPipeEventEnabledMethodLoadVerbose_V1();
ULONG EventPipeWriteEventMethodLoadVerbose_V1(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    PCWSTR  MethodNamespace,
    PCWSTR  MethodName,
    PCWSTR  MethodSignature,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodLoadVerbose_V2();
ULONG EventPipeWriteEventMethodLoadVerbose_V2(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    PCWSTR  MethodNamespace,
    PCWSTR  MethodName,
    PCWSTR  MethodSignature,
    const unsigned short  ClrInstanceID,
    const unsigned __int64  ReJITID
);
BOOL EventPipeEventEnabledMethodUnloadVerbose();
ULONG EventPipeWriteEventMethodUnloadVerbose(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    PCWSTR  MethodNamespace,
    PCWSTR  MethodName,
    PCWSTR  MethodSignature
);
BOOL EventPipeEventEnabledMethodUnloadVerbose_V1();
ULONG EventPipeWriteEventMethodUnloadVerbose_V1(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    PCWSTR  MethodNamespace,
    PCWSTR  MethodName,
    PCWSTR  MethodSignature,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodUnloadVerbose_V2();
ULONG EventPipeWriteEventMethodUnloadVerbose_V2(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    PCWSTR  MethodNamespace,
    PCWSTR  MethodName,
    PCWSTR  MethodSignature,
    const unsigned short  ClrInstanceID,
    const unsigned __int64  ReJITID
);
BOOL EventPipeEventEnabledMethodJittingStarted();
ULONG EventPipeWriteEventMethodJittingStarted(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned int  MethodToken,
    const unsigned int  MethodILSize,
    PCWSTR  MethodNamespace,
    PCWSTR  MethodName,
    PCWSTR  MethodSignature
);
BOOL EventPipeEventEnabledMethodJittingStarted_V1();
ULONG EventPipeWriteEventMethodJittingStarted_V1(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned int  MethodToken,
    const unsigned int  MethodILSize,
    PCWSTR  MethodNamespace,
    PCWSTR  MethodName,
    PCWSTR  MethodSignature,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodJitInliningSucceeded();
ULONG EventPipeWriteEventMethodJitInliningSucceeded(
    PCWSTR  MethodBeingCompiledNamespace,
    PCWSTR  MethodBeingCompiledName,
    PCWSTR  MethodBeingCompiledNameSignature,
    PCWSTR  InlinerNamespace,
    PCWSTR  InlinerName,
    PCWSTR  InlinerNameSignature,
    PCWSTR  InlineeNamespace,
    PCWSTR  InlineeName,
    PCWSTR  InlineeNameSignature,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodJitInliningFailed();
ULONG EventPipeWriteEventMethodJitInliningFailed(
    PCWSTR  MethodBeingCompiledNamespace,
    PCWSTR  MethodBeingCompiledName,
    PCWSTR  MethodBeingCompiledNameSignature,
    PCWSTR  InlinerNamespace,
    PCWSTR  InlinerName,
    PCWSTR  InlinerNameSignature,
    PCWSTR  InlineeNamespace,
    PCWSTR  InlineeName,
    PCWSTR  InlineeNameSignature,
    const BOOL  FailAlways,
    LPCSTR  FailReason,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodJitTailCallSucceeded();
ULONG EventPipeWriteEventMethodJitTailCallSucceeded(
    PCWSTR  MethodBeingCompiledNamespace,
    PCWSTR  MethodBeingCompiledName,
    PCWSTR  MethodBeingCompiledNameSignature,
    PCWSTR  CallerNamespace,
    PCWSTR  CallerName,
    PCWSTR  CallerNameSignature,
    PCWSTR  CalleeNamespace,
    PCWSTR  CalleeName,
    PCWSTR  CalleeNameSignature,
    const BOOL  TailPrefix,
    const unsigned int  TailCallType,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodJitTailCallFailed();
ULONG EventPipeWriteEventMethodJitTailCallFailed(
    PCWSTR  MethodBeingCompiledNamespace,
    PCWSTR  MethodBeingCompiledName,
    PCWSTR  MethodBeingCompiledNameSignature,
    PCWSTR  CallerNamespace,
    PCWSTR  CallerName,
    PCWSTR  CallerNameSignature,
    PCWSTR  CalleeNamespace,
    PCWSTR  CalleeName,
    PCWSTR  CalleeNameSignature,
    const BOOL  TailPrefix,
    LPCSTR  FailReason,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodILToNativeMap();
ULONG EventPipeWriteEventMethodILToNativeMap(
    const unsigned __int64  MethodID,
    const unsigned __int64  ReJITID,
    const unsigned char  MethodExtent,
    const unsigned short  CountOfMapEntries,
    const unsigned int* ILOffsets,
    const unsigned int* NativeOffsets,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledModuleDCStartV2();
ULONG EventPipeWriteEventModuleDCStartV2(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath
);
BOOL EventPipeEventEnabledModuleDCEndV2();
ULONG EventPipeWriteEventModuleDCEndV2(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath
);
BOOL EventPipeEventEnabledDomainModuleLoad();
ULONG EventPipeWriteEventDomainModuleLoad(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned __int64  AppDomainID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath
);
BOOL EventPipeEventEnabledDomainModuleLoad_V1();
ULONG EventPipeWriteEventDomainModuleLoad_V1(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned __int64  AppDomainID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledModuleLoad();
ULONG EventPipeWriteEventModuleLoad(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath
);
BOOL EventPipeEventEnabledModuleLoad_V1();
ULONG EventPipeWriteEventModuleLoad_V1(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledModuleLoad_V2();
ULONG EventPipeWriteEventModuleLoad_V2(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath,
    const unsigned short  ClrInstanceID,
    const GUID* ManagedPdbSignature,
    const unsigned int  ManagedPdbAge,
    PCWSTR  ManagedPdbBuildPath,
    const GUID* NativePdbSignature,
    const unsigned int  NativePdbAge,
    PCWSTR  NativePdbBuildPath
);
BOOL EventPipeEventEnabledModuleUnload();
ULONG EventPipeWriteEventModuleUnload(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath
);
BOOL EventPipeEventEnabledModuleUnload_V1();
ULONG EventPipeWriteEventModuleUnload_V1(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledModuleUnload_V2();
ULONG EventPipeWriteEventModuleUnload_V2(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath,
    const unsigned short  ClrInstanceID,
    const GUID* ManagedPdbSignature,
    const unsigned int  ManagedPdbAge,
    PCWSTR  ManagedPdbBuildPath,
    const GUID* NativePdbSignature,
    const unsigned int  NativePdbAge,
    PCWSTR  NativePdbBuildPath
);
BOOL EventPipeEventEnabledAssemblyLoad();
ULONG EventPipeWriteEventAssemblyLoad(
    const unsigned __int64  AssemblyID,
    const unsigned __int64  AppDomainID,
    const unsigned int  AssemblyFlags,
    PCWSTR  FullyQualifiedAssemblyName
);
BOOL EventPipeEventEnabledAssemblyLoad_V1();
ULONG EventPipeWriteEventAssemblyLoad_V1(
    const unsigned __int64  AssemblyID,
    const unsigned __int64  AppDomainID,
    const unsigned __int64  BindingID,
    const unsigned int  AssemblyFlags,
    PCWSTR  FullyQualifiedAssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledAssemblyUnload();
ULONG EventPipeWriteEventAssemblyUnload(
    const unsigned __int64  AssemblyID,
    const unsigned __int64  AppDomainID,
    const unsigned int  AssemblyFlags,
    PCWSTR  FullyQualifiedAssemblyName
);
BOOL EventPipeEventEnabledAssemblyUnload_V1();
ULONG EventPipeWriteEventAssemblyUnload_V1(
    const unsigned __int64  AssemblyID,
    const unsigned __int64  AppDomainID,
    const unsigned __int64  BindingID,
    const unsigned int  AssemblyFlags,
    PCWSTR  FullyQualifiedAssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledAppDomainLoad();
ULONG EventPipeWriteEventAppDomainLoad(
    const unsigned __int64  AppDomainID,
    const unsigned int  AppDomainFlags,
    PCWSTR  AppDomainName
);
BOOL EventPipeEventEnabledAppDomainLoad_V1();
ULONG EventPipeWriteEventAppDomainLoad_V1(
    const unsigned __int64  AppDomainID,
    const unsigned int  AppDomainFlags,
    PCWSTR  AppDomainName,
    const unsigned int  AppDomainIndex,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledAppDomainUnload();
ULONG EventPipeWriteEventAppDomainUnload(
    const unsigned __int64  AppDomainID,
    const unsigned int  AppDomainFlags,
    PCWSTR  AppDomainName
);
BOOL EventPipeEventEnabledAppDomainUnload_V1();
ULONG EventPipeWriteEventAppDomainUnload_V1(
    const unsigned __int64  AppDomainID,
    const unsigned int  AppDomainFlags,
    PCWSTR  AppDomainName,
    const unsigned int  AppDomainIndex,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledModuleRangeLoad();
ULONG EventPipeWriteEventModuleRangeLoad(
    const unsigned short  ClrInstanceID,
    const unsigned __int64  ModuleID,
    const unsigned int  RangeBegin,
    const unsigned int  RangeSize,
    const unsigned char  RangeType
);
BOOL EventPipeEventEnabledStrongNameVerificationStart();
ULONG EventPipeWriteEventStrongNameVerificationStart(
    const unsigned int  VerificationFlags,
    const unsigned int  ErrorCode,
    PCWSTR  FullyQualifiedAssemblyName
);
BOOL EventPipeEventEnabledStrongNameVerificationStart_V1();
ULONG EventPipeWriteEventStrongNameVerificationStart_V1(
    const unsigned int  VerificationFlags,
    const unsigned int  ErrorCode,
    PCWSTR  FullyQualifiedAssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledStrongNameVerificationStop();
ULONG EventPipeWriteEventStrongNameVerificationStop(
    const unsigned int  VerificationFlags,
    const unsigned int  ErrorCode,
    PCWSTR  FullyQualifiedAssemblyName
);
BOOL EventPipeEventEnabledStrongNameVerificationStop_V1();
ULONG EventPipeWriteEventStrongNameVerificationStop_V1(
    const unsigned int  VerificationFlags,
    const unsigned int  ErrorCode,
    PCWSTR  FullyQualifiedAssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledAuthenticodeVerificationStart();
ULONG EventPipeWriteEventAuthenticodeVerificationStart(
    const unsigned int  VerificationFlags,
    const unsigned int  ErrorCode,
    PCWSTR  ModulePath
);
BOOL EventPipeEventEnabledAuthenticodeVerificationStart_V1();
ULONG EventPipeWriteEventAuthenticodeVerificationStart_V1(
    const unsigned int  VerificationFlags,
    const unsigned int  ErrorCode,
    PCWSTR  ModulePath,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledAuthenticodeVerificationStop();
ULONG EventPipeWriteEventAuthenticodeVerificationStop(
    const unsigned int  VerificationFlags,
    const unsigned int  ErrorCode,
    PCWSTR  ModulePath
);
BOOL EventPipeEventEnabledAuthenticodeVerificationStop_V1();
ULONG EventPipeWriteEventAuthenticodeVerificationStop_V1(
    const unsigned int  VerificationFlags,
    const unsigned int  ErrorCode,
    PCWSTR  ModulePath,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledRuntimeInformationStart();
ULONG EventPipeWriteEventRuntimeInformationStart(
    const unsigned short  ClrInstanceID,
    const unsigned short  Sku,
    const unsigned short  BclMajorVersion,
    const unsigned short  BclMinorVersion,
    const unsigned short  BclBuildNumber,
    const unsigned short  BclQfeNumber,
    const unsigned short  VMMajorVersion,
    const unsigned short  VMMinorVersion,
    const unsigned short  VMBuildNumber,
    const unsigned short  VMQfeNumber,
    const unsigned int  StartupFlags,
    const unsigned char  StartupMode,
    PCWSTR  CommandLine,
    const GUID* ComObjectGuid,
    PCWSTR  RuntimeDllPath
);
BOOL EventPipeEventEnabledIncreaseMemoryPressure();
ULONG EventPipeWriteEventIncreaseMemoryPressure(
    const unsigned __int64  BytesAllocated,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledDecreaseMemoryPressure();
ULONG EventPipeWriteEventDecreaseMemoryPressure(
    const unsigned __int64  BytesFreed,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCMarkWithType();
ULONG EventPipeWriteEventGCMarkWithType(
    const unsigned int  HeapNum,
    const unsigned short  ClrInstanceID,
    const unsigned int  Type,
    const unsigned __int64  Bytes
);
BOOL EventPipeEventEnabledGCJoin_V2();
ULONG EventPipeWriteEventGCJoin_V2(
    const unsigned int  Heap,
    const unsigned int  JoinTime,
    const unsigned int  JoinType,
    const unsigned short  ClrInstanceID,
    const unsigned int  JoinID
);
BOOL EventPipeEventEnabledGCPerHeapHistory_V3();
ULONG EventPipeWriteEventGCPerHeapHistory_V3(
    const unsigned short  ClrInstanceID,
    const void*  FreeListAllocated,
    const void*  FreeListRejected,
    const void*  EndOfSegAllocated,
    const void*  CondemnedAllocated,
    const void*  PinnedAllocated,
    const void*  PinnedAllocatedAdvance,
    const unsigned int  RunningFreeListEfficiency,
    const unsigned int  CondemnReasons0,
    const unsigned int  CondemnReasons1,
    const unsigned int  CompactMechanisms,
    const unsigned int  ExpandMechanisms,
    const unsigned int  HeapIndex,
    const void*  ExtraGen0Commit,
    const unsigned int  Count,
    int Values_ElementSize,
    const void* Values
);
BOOL EventPipeEventEnabledGCGlobalHeapHistory_V2();
ULONG EventPipeWriteEventGCGlobalHeapHistory_V2(
    const unsigned __int64  FinalYoungestDesired,
    const signed int  NumHeaps,
    const unsigned int  CondemnedGeneration,
    const unsigned int  Gen0ReductionCount,
    const unsigned int  Reason,
    const unsigned int  GlobalMechanisms,
    const unsigned short  ClrInstanceID,
    const unsigned int  PauseMode,
    const unsigned int  MemoryPressure
);
BOOL EventPipeEventEnabledDebugIPCEventStart();
ULONG EventPipeWriteEventDebugIPCEventStart(

);
BOOL EventPipeEventEnabledDebugIPCEventEnd();
ULONG EventPipeWriteEventDebugIPCEventEnd(

);
BOOL EventPipeEventEnabledDebugExceptionProcessingStart();
ULONG EventPipeWriteEventDebugExceptionProcessingStart(

);
BOOL EventPipeEventEnabledDebugExceptionProcessingEnd();
ULONG EventPipeWriteEventDebugExceptionProcessingEnd(

);
BOOL EventPipeEventEnabledCodeSymbols();
ULONG EventPipeWriteEventCodeSymbols(
    const unsigned __int64  ModuleId,
    const unsigned short  TotalChunks,
    const unsigned short  ChunkNumber,
    const unsigned int  ChunkLength,
    const BYTE* Chunk,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledEventSource();
ULONG EventPipeWriteEventEventSource(
    const signed int  EventID,
    PCWSTR  EventName,
    PCWSTR  EventSourceName,
    PCWSTR  Payload
);

BOOL EventPipeEventEnabledCLRStackWalkDCStart();
ULONG EventPipeWriteEventCLRStackWalkDCStart(
    const unsigned short  ClrInstanceID,
    const unsigned char  Reserved1,
    const unsigned char  Reserved2,
    const unsigned int  FrameCount,
    const void** Stack
);
BOOL EventPipeEventEnabledMethodDCStart();
ULONG EventPipeWriteEventMethodDCStart(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags
);
BOOL EventPipeEventEnabledMethodDCStart_V1();
ULONG EventPipeWriteEventMethodDCStart_V1(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodDCStart_V2();
ULONG EventPipeWriteEventMethodDCStart_V2(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    const unsigned short  ClrInstanceID,
    const unsigned __int64  ReJITID
);
BOOL EventPipeEventEnabledMethodDCEnd();
ULONG EventPipeWriteEventMethodDCEnd(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags
);
BOOL EventPipeEventEnabledMethodDCEnd_V1();
ULONG EventPipeWriteEventMethodDCEnd_V1(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodDCEnd_V2();
ULONG EventPipeWriteEventMethodDCEnd_V2(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    const unsigned short  ClrInstanceID,
    const unsigned __int64  ReJITID
);
BOOL EventPipeEventEnabledMethodDCStartVerbose();
ULONG EventPipeWriteEventMethodDCStartVerbose(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    PCWSTR  MethodNamespace,
    PCWSTR  MethodName,
    PCWSTR  MethodSignature
);
BOOL EventPipeEventEnabledMethodDCStartVerbose_V1();
ULONG EventPipeWriteEventMethodDCStartVerbose_V1(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    PCWSTR  MethodNamespace,
    PCWSTR  MethodName,
    PCWSTR  MethodSignature,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodDCStartVerbose_V2();
ULONG EventPipeWriteEventMethodDCStartVerbose_V2(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    PCWSTR  MethodNamespace,
    PCWSTR  MethodName,
    PCWSTR  MethodSignature,
    const unsigned short  ClrInstanceID,
    const unsigned __int64  ReJITID
);
BOOL EventPipeEventEnabledMethodDCEndVerbose();
ULONG EventPipeWriteEventMethodDCEndVerbose(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    PCWSTR  MethodNamespace,
    PCWSTR  MethodName,
    PCWSTR  MethodSignature
);
BOOL EventPipeEventEnabledMethodDCEndVerbose_V1();
ULONG EventPipeWriteEventMethodDCEndVerbose_V1(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    PCWSTR  MethodNamespace,
    PCWSTR  MethodName,
    PCWSTR  MethodSignature,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodDCEndVerbose_V2();
ULONG EventPipeWriteEventMethodDCEndVerbose_V2(
    const unsigned __int64  MethodID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodStartAddress,
    const unsigned int  MethodSize,
    const unsigned int  MethodToken,
    const unsigned int  MethodFlags,
    PCWSTR  MethodNamespace,
    PCWSTR  MethodName,
    PCWSTR  MethodSignature,
    const unsigned short  ClrInstanceID,
    const unsigned __int64  ReJITID
);
BOOL EventPipeEventEnabledDCStartComplete();
ULONG EventPipeWriteEventDCStartComplete(

);
BOOL EventPipeEventEnabledDCStartComplete_V1();
ULONG EventPipeWriteEventDCStartComplete_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledDCEndComplete();
ULONG EventPipeWriteEventDCEndComplete(

);
BOOL EventPipeEventEnabledDCEndComplete_V1();
ULONG EventPipeWriteEventDCEndComplete_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledDCStartInit();
ULONG EventPipeWriteEventDCStartInit(

);
BOOL EventPipeEventEnabledDCStartInit_V1();
ULONG EventPipeWriteEventDCStartInit_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledDCEndInit();
ULONG EventPipeWriteEventDCEndInit(

);
BOOL EventPipeEventEnabledDCEndInit_V1();
ULONG EventPipeWriteEventDCEndInit_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodDCStartILToNativeMap();
ULONG EventPipeWriteEventMethodDCStartILToNativeMap(
    const unsigned __int64  MethodID,
    const unsigned __int64  ReJITID,
    const unsigned char  MethodExtent,
    const unsigned short  CountOfMapEntries,
    const unsigned int* ILOffsets,
    const unsigned int* NativeOffsets,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodDCEndILToNativeMap();
ULONG EventPipeWriteEventMethodDCEndILToNativeMap(
    const unsigned __int64  MethodID,
    const unsigned __int64  ReJITID,
    const unsigned char  MethodExtent,
    const unsigned short  CountOfMapEntries,
    const unsigned int* ILOffsets,
    const unsigned int* NativeOffsets,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledDomainModuleDCStart();
ULONG EventPipeWriteEventDomainModuleDCStart(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned __int64  AppDomainID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath
);
BOOL EventPipeEventEnabledDomainModuleDCStart_V1();
ULONG EventPipeWriteEventDomainModuleDCStart_V1(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned __int64  AppDomainID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledDomainModuleDCEnd();
ULONG EventPipeWriteEventDomainModuleDCEnd(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned __int64  AppDomainID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath
);
BOOL EventPipeEventEnabledDomainModuleDCEnd_V1();
ULONG EventPipeWriteEventDomainModuleDCEnd_V1(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned __int64  AppDomainID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledModuleDCStart();
ULONG EventPipeWriteEventModuleDCStart(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath
);
BOOL EventPipeEventEnabledModuleDCStart_V1();
ULONG EventPipeWriteEventModuleDCStart_V1(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledModuleDCStart_V2();
ULONG EventPipeWriteEventModuleDCStart_V2(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath,
    const unsigned short  ClrInstanceID,
    const GUID* ManagedPdbSignature,
    const unsigned int  ManagedPdbAge,
    PCWSTR  ManagedPdbBuildPath,
    const GUID* NativePdbSignature,
    const unsigned int  NativePdbAge,
    PCWSTR  NativePdbBuildPath
);
BOOL EventPipeEventEnabledModuleDCEnd();
ULONG EventPipeWriteEventModuleDCEnd(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath
);
BOOL EventPipeEventEnabledModuleDCEnd_V1();
ULONG EventPipeWriteEventModuleDCEnd_V1(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledModuleDCEnd_V2();
ULONG EventPipeWriteEventModuleDCEnd_V2(
    const unsigned __int64  ModuleID,
    const unsigned __int64  AssemblyID,
    const unsigned int  ModuleFlags,
    const unsigned int  Reserved1,
    PCWSTR  ModuleILPath,
    PCWSTR  ModuleNativePath,
    const unsigned short  ClrInstanceID,
    const GUID* ManagedPdbSignature,
    const unsigned int  ManagedPdbAge,
    PCWSTR  ManagedPdbBuildPath,
    const GUID* NativePdbSignature,
    const unsigned int  NativePdbAge,
    PCWSTR  NativePdbBuildPath
);
BOOL EventPipeEventEnabledAssemblyDCStart();
ULONG EventPipeWriteEventAssemblyDCStart(
    const unsigned __int64  AssemblyID,
    const unsigned __int64  AppDomainID,
    const unsigned int  AssemblyFlags,
    PCWSTR  FullyQualifiedAssemblyName
);
BOOL EventPipeEventEnabledAssemblyDCStart_V1();
ULONG EventPipeWriteEventAssemblyDCStart_V1(
    const unsigned __int64  AssemblyID,
    const unsigned __int64  AppDomainID,
    const unsigned __int64  BindingID,
    const unsigned int  AssemblyFlags,
    PCWSTR  FullyQualifiedAssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledAssemblyDCEnd();
ULONG EventPipeWriteEventAssemblyDCEnd(
    const unsigned __int64  AssemblyID,
    const unsigned __int64  AppDomainID,
    const unsigned int  AssemblyFlags,
    PCWSTR  FullyQualifiedAssemblyName
);
BOOL EventPipeEventEnabledAssemblyDCEnd_V1();
ULONG EventPipeWriteEventAssemblyDCEnd_V1(
    const unsigned __int64  AssemblyID,
    const unsigned __int64  AppDomainID,
    const unsigned __int64  BindingID,
    const unsigned int  AssemblyFlags,
    PCWSTR  FullyQualifiedAssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledAppDomainDCStart();
ULONG EventPipeWriteEventAppDomainDCStart(
    const unsigned __int64  AppDomainID,
    const unsigned int  AppDomainFlags,
    PCWSTR  AppDomainName
);
BOOL EventPipeEventEnabledAppDomainDCStart_V1();
ULONG EventPipeWriteEventAppDomainDCStart_V1(
    const unsigned __int64  AppDomainID,
    const unsigned int  AppDomainFlags,
    PCWSTR  AppDomainName,
    const unsigned int  AppDomainIndex,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledAppDomainDCEnd();
ULONG EventPipeWriteEventAppDomainDCEnd(
    const unsigned __int64  AppDomainID,
    const unsigned int  AppDomainFlags,
    PCWSTR  AppDomainName
);
BOOL EventPipeEventEnabledAppDomainDCEnd_V1();
ULONG EventPipeWriteEventAppDomainDCEnd_V1(
    const unsigned __int64  AppDomainID,
    const unsigned int  AppDomainFlags,
    PCWSTR  AppDomainName,
    const unsigned int  AppDomainIndex,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledThreadDC();
ULONG EventPipeWriteEventThreadDC(
    const unsigned __int64  ManagedThreadID,
    const unsigned __int64  AppDomainID,
    const unsigned int  Flags,
    const unsigned int  ManagedThreadIndex,
    const unsigned int  OSThreadID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledModuleRangeDCStart();
ULONG EventPipeWriteEventModuleRangeDCStart(
    const unsigned short  ClrInstanceID,
    const unsigned __int64  ModuleID,
    const unsigned int  RangeBegin,
    const unsigned int  RangeSize,
    const unsigned char  RangeType
);
BOOL EventPipeEventEnabledModuleRangeDCEnd();
ULONG EventPipeWriteEventModuleRangeDCEnd(
    const unsigned short  ClrInstanceID,
    const unsigned __int64  ModuleID,
    const unsigned int  RangeBegin,
    const unsigned int  RangeSize,
    const unsigned char  RangeType
);
BOOL EventPipeEventEnabledRuntimeInformationDCStart();
ULONG EventPipeWriteEventRuntimeInformationDCStart(
    const unsigned short  ClrInstanceID,
    const unsigned short  Sku,
    const unsigned short  BclMajorVersion,
    const unsigned short  BclMinorVersion,
    const unsigned short  BclBuildNumber,
    const unsigned short  BclQfeNumber,
    const unsigned short  VMMajorVersion,
    const unsigned short  VMMinorVersion,
    const unsigned short  VMBuildNumber,
    const unsigned short  VMQfeNumber,
    const unsigned int  StartupFlags,
    const unsigned char  StartupMode,
    PCWSTR  CommandLine,
    const GUID* ComObjectGuid,
    PCWSTR  RuntimeDllPath
);

BOOL EventPipeEventEnabledStressLogEvent();
ULONG EventPipeWriteEventStressLogEvent(
    const unsigned int  Facility,
    const unsigned char  LogLevel,
    LPCSTR  Message
);
BOOL EventPipeEventEnabledStressLogEvent_V1();
ULONG EventPipeWriteEventStressLogEvent_V1(
    const unsigned int  Facility,
    const unsigned char  LogLevel,
    LPCSTR  Message,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledCLRStackWalkStress();
ULONG EventPipeWriteEventCLRStackWalkStress(
    const unsigned short  ClrInstanceID,
    const unsigned char  Reserved1,
    const unsigned char  Reserved2,
    const unsigned int  FrameCount,
    const void** Stack
);

BOOL EventPipeEventEnabledGCDecision();
ULONG EventPipeWriteEventGCDecision(
    const BOOL  DoCompact
);
BOOL EventPipeEventEnabledGCDecision_V1();
ULONG EventPipeWriteEventGCDecision_V1(
    const BOOL  DoCompact,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCSettings();
ULONG EventPipeWriteEventGCSettings(
    const unsigned __int64  SegmentSize,
    const unsigned __int64  LargeObjectSegmentSize,
    const BOOL  ServerGC
);
BOOL EventPipeEventEnabledGCSettings_V1();
ULONG EventPipeWriteEventGCSettings_V1(
    const unsigned __int64  SegmentSize,
    const unsigned __int64  LargeObjectSegmentSize,
    const BOOL  ServerGC,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCOptimized();
ULONG EventPipeWriteEventGCOptimized(
    const unsigned __int64  DesiredAllocation,
    const unsigned __int64  NewAllocation,
    const unsigned int  GenerationNumber
);
BOOL EventPipeEventEnabledGCOptimized_V1();
ULONG EventPipeWriteEventGCOptimized_V1(
    const unsigned __int64  DesiredAllocation,
    const unsigned __int64  NewAllocation,
    const unsigned int  GenerationNumber,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCPerHeapHistory();
ULONG EventPipeWriteEventGCPerHeapHistory(

);
BOOL EventPipeEventEnabledGCPerHeapHistory_V1();
ULONG EventPipeWriteEventGCPerHeapHistory_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCGlobalHeapHistory();
ULONG EventPipeWriteEventGCGlobalHeapHistory(
    const unsigned __int64  FinalYoungestDesired,
    const signed int  NumHeaps,
    const unsigned int  CondemnedGeneration,
    const unsigned int  Gen0ReductionCount,
    const unsigned int  Reason,
    const unsigned int  GlobalMechanisms
);
BOOL EventPipeEventEnabledGCGlobalHeapHistory_V1();
ULONG EventPipeWriteEventGCGlobalHeapHistory_V1(
    const unsigned __int64  FinalYoungestDesired,
    const signed int  NumHeaps,
    const unsigned int  CondemnedGeneration,
    const unsigned int  Gen0ReductionCount,
    const unsigned int  Reason,
    const unsigned int  GlobalMechanisms,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCJoin();
ULONG EventPipeWriteEventGCJoin(
    const unsigned int  Heap,
    const unsigned int  JoinTime,
    const unsigned int  JoinType
);
BOOL EventPipeEventEnabledGCJoin_V1();
ULONG EventPipeWriteEventGCJoin_V1(
    const unsigned int  Heap,
    const unsigned int  JoinTime,
    const unsigned int  JoinType,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledPrvGCMarkStackRoots();
ULONG EventPipeWriteEventPrvGCMarkStackRoots(
    const unsigned int  HeapNum
);
BOOL EventPipeEventEnabledPrvGCMarkStackRoots_V1();
ULONG EventPipeWriteEventPrvGCMarkStackRoots_V1(
    const unsigned int  HeapNum,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledPrvGCMarkFinalizeQueueRoots();
ULONG EventPipeWriteEventPrvGCMarkFinalizeQueueRoots(
    const unsigned int  HeapNum
);
BOOL EventPipeEventEnabledPrvGCMarkFinalizeQueueRoots_V1();
ULONG EventPipeWriteEventPrvGCMarkFinalizeQueueRoots_V1(
    const unsigned int  HeapNum,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledPrvGCMarkHandles();
ULONG EventPipeWriteEventPrvGCMarkHandles(
    const unsigned int  HeapNum
);
BOOL EventPipeEventEnabledPrvGCMarkHandles_V1();
ULONG EventPipeWriteEventPrvGCMarkHandles_V1(
    const unsigned int  HeapNum,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledPrvGCMarkCards();
ULONG EventPipeWriteEventPrvGCMarkCards(
    const unsigned int  HeapNum
);
BOOL EventPipeEventEnabledPrvGCMarkCards_V1();
ULONG EventPipeWriteEventPrvGCMarkCards_V1(
    const unsigned int  HeapNum,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBGCBegin();
ULONG EventPipeWriteEventBGCBegin(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBGC1stNonConEnd();
ULONG EventPipeWriteEventBGC1stNonConEnd(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBGC1stConEnd();
ULONG EventPipeWriteEventBGC1stConEnd(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBGC2ndNonConBegin();
ULONG EventPipeWriteEventBGC2ndNonConBegin(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBGC2ndNonConEnd();
ULONG EventPipeWriteEventBGC2ndNonConEnd(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBGC2ndConBegin();
ULONG EventPipeWriteEventBGC2ndConBegin(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBGC2ndConEnd();
ULONG EventPipeWriteEventBGC2ndConEnd(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBGCPlanEnd();
ULONG EventPipeWriteEventBGCPlanEnd(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBGCSweepEnd();
ULONG EventPipeWriteEventBGCSweepEnd(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBGCDrainMark();
ULONG EventPipeWriteEventBGCDrainMark(
    const unsigned __int64  Objects,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBGCRevisit();
ULONG EventPipeWriteEventBGCRevisit(
    const unsigned __int64  Pages,
    const unsigned __int64  Objects,
    const unsigned int  IsLarge,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBGCOverflow();
ULONG EventPipeWriteEventBGCOverflow(
    const unsigned __int64  Min,
    const unsigned __int64  Max,
    const unsigned __int64  Objects,
    const unsigned int  IsLarge,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBGCAllocWaitBegin();
ULONG EventPipeWriteEventBGCAllocWaitBegin(
    const unsigned int  Reason,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBGCAllocWaitEnd();
ULONG EventPipeWriteEventBGCAllocWaitEnd(
    const unsigned int  Reason,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGCFullNotify();
ULONG EventPipeWriteEventGCFullNotify(
    const unsigned int  GenNumber,
    const unsigned int  IsAlloc
);
BOOL EventPipeEventEnabledGCFullNotify_V1();
ULONG EventPipeWriteEventGCFullNotify_V1(
    const unsigned int  GenNumber,
    const unsigned int  IsAlloc,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledEEStartupStart();
ULONG EventPipeWriteEventEEStartupStart(

);
BOOL EventPipeEventEnabledEEStartupStart_V1();
ULONG EventPipeWriteEventEEStartupStart_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledEEStartupEnd();
ULONG EventPipeWriteEventEEStartupEnd(

);
BOOL EventPipeEventEnabledEEStartupEnd_V1();
ULONG EventPipeWriteEventEEStartupEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledEEConfigSetup();
ULONG EventPipeWriteEventEEConfigSetup(

);
BOOL EventPipeEventEnabledEEConfigSetup_V1();
ULONG EventPipeWriteEventEEConfigSetup_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledEEConfigSetupEnd();
ULONG EventPipeWriteEventEEConfigSetupEnd(

);
BOOL EventPipeEventEnabledEEConfigSetupEnd_V1();
ULONG EventPipeWriteEventEEConfigSetupEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledLdSysBases();
ULONG EventPipeWriteEventLdSysBases(

);
BOOL EventPipeEventEnabledLdSysBases_V1();
ULONG EventPipeWriteEventLdSysBases_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledLdSysBasesEnd();
ULONG EventPipeWriteEventLdSysBasesEnd(

);
BOOL EventPipeEventEnabledLdSysBasesEnd_V1();
ULONG EventPipeWriteEventLdSysBasesEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledExecExe();
ULONG EventPipeWriteEventExecExe(

);
BOOL EventPipeEventEnabledExecExe_V1();
ULONG EventPipeWriteEventExecExe_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledExecExeEnd();
ULONG EventPipeWriteEventExecExeEnd(

);
BOOL EventPipeEventEnabledExecExeEnd_V1();
ULONG EventPipeWriteEventExecExeEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMain();
ULONG EventPipeWriteEventMain(

);
BOOL EventPipeEventEnabledMain_V1();
ULONG EventPipeWriteEventMain_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMainEnd();
ULONG EventPipeWriteEventMainEnd(

);
BOOL EventPipeEventEnabledMainEnd_V1();
ULONG EventPipeWriteEventMainEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledApplyPolicyStart();
ULONG EventPipeWriteEventApplyPolicyStart(

);
BOOL EventPipeEventEnabledApplyPolicyStart_V1();
ULONG EventPipeWriteEventApplyPolicyStart_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledApplyPolicyEnd();
ULONG EventPipeWriteEventApplyPolicyEnd(

);
BOOL EventPipeEventEnabledApplyPolicyEnd_V1();
ULONG EventPipeWriteEventApplyPolicyEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledLdLibShFolder();
ULONG EventPipeWriteEventLdLibShFolder(

);
BOOL EventPipeEventEnabledLdLibShFolder_V1();
ULONG EventPipeWriteEventLdLibShFolder_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledLdLibShFolderEnd();
ULONG EventPipeWriteEventLdLibShFolderEnd(

);
BOOL EventPipeEventEnabledLdLibShFolderEnd_V1();
ULONG EventPipeWriteEventLdLibShFolderEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledPrestubWorker();
ULONG EventPipeWriteEventPrestubWorker(

);
BOOL EventPipeEventEnabledPrestubWorker_V1();
ULONG EventPipeWriteEventPrestubWorker_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledPrestubWorkerEnd();
ULONG EventPipeWriteEventPrestubWorkerEnd(

);
BOOL EventPipeEventEnabledPrestubWorkerEnd_V1();
ULONG EventPipeWriteEventPrestubWorkerEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGetInstallationStart();
ULONG EventPipeWriteEventGetInstallationStart(

);
BOOL EventPipeEventEnabledGetInstallationStart_V1();
ULONG EventPipeWriteEventGetInstallationStart_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGetInstallationEnd();
ULONG EventPipeWriteEventGetInstallationEnd(

);
BOOL EventPipeEventEnabledGetInstallationEnd_V1();
ULONG EventPipeWriteEventGetInstallationEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledOpenHModule();
ULONG EventPipeWriteEventOpenHModule(

);
BOOL EventPipeEventEnabledOpenHModule_V1();
ULONG EventPipeWriteEventOpenHModule_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledOpenHModuleEnd();
ULONG EventPipeWriteEventOpenHModuleEnd(

);
BOOL EventPipeEventEnabledOpenHModuleEnd_V1();
ULONG EventPipeWriteEventOpenHModuleEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledExplicitBindStart();
ULONG EventPipeWriteEventExplicitBindStart(

);
BOOL EventPipeEventEnabledExplicitBindStart_V1();
ULONG EventPipeWriteEventExplicitBindStart_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledExplicitBindEnd();
ULONG EventPipeWriteEventExplicitBindEnd(

);
BOOL EventPipeEventEnabledExplicitBindEnd_V1();
ULONG EventPipeWriteEventExplicitBindEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledParseXml();
ULONG EventPipeWriteEventParseXml(

);
BOOL EventPipeEventEnabledParseXml_V1();
ULONG EventPipeWriteEventParseXml_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledParseXmlEnd();
ULONG EventPipeWriteEventParseXmlEnd(

);
BOOL EventPipeEventEnabledParseXmlEnd_V1();
ULONG EventPipeWriteEventParseXmlEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledInitDefaultDomain();
ULONG EventPipeWriteEventInitDefaultDomain(

);
BOOL EventPipeEventEnabledInitDefaultDomain_V1();
ULONG EventPipeWriteEventInitDefaultDomain_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledInitDefaultDomainEnd();
ULONG EventPipeWriteEventInitDefaultDomainEnd(

);
BOOL EventPipeEventEnabledInitDefaultDomainEnd_V1();
ULONG EventPipeWriteEventInitDefaultDomainEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledInitSecurity();
ULONG EventPipeWriteEventInitSecurity(

);
BOOL EventPipeEventEnabledInitSecurity_V1();
ULONG EventPipeWriteEventInitSecurity_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledInitSecurityEnd();
ULONG EventPipeWriteEventInitSecurityEnd(

);
BOOL EventPipeEventEnabledInitSecurityEnd_V1();
ULONG EventPipeWriteEventInitSecurityEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledAllowBindingRedirs();
ULONG EventPipeWriteEventAllowBindingRedirs(

);
BOOL EventPipeEventEnabledAllowBindingRedirs_V1();
ULONG EventPipeWriteEventAllowBindingRedirs_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledAllowBindingRedirsEnd();
ULONG EventPipeWriteEventAllowBindingRedirsEnd(

);
BOOL EventPipeEventEnabledAllowBindingRedirsEnd_V1();
ULONG EventPipeWriteEventAllowBindingRedirsEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledEEConfigSync();
ULONG EventPipeWriteEventEEConfigSync(

);
BOOL EventPipeEventEnabledEEConfigSync_V1();
ULONG EventPipeWriteEventEEConfigSync_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledEEConfigSyncEnd();
ULONG EventPipeWriteEventEEConfigSyncEnd(

);
BOOL EventPipeEventEnabledEEConfigSyncEnd_V1();
ULONG EventPipeWriteEventEEConfigSyncEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledFusionBinding();
ULONG EventPipeWriteEventFusionBinding(

);
BOOL EventPipeEventEnabledFusionBinding_V1();
ULONG EventPipeWriteEventFusionBinding_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledFusionBindingEnd();
ULONG EventPipeWriteEventFusionBindingEnd(

);
BOOL EventPipeEventEnabledFusionBindingEnd_V1();
ULONG EventPipeWriteEventFusionBindingEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledLoaderCatchCall();
ULONG EventPipeWriteEventLoaderCatchCall(

);
BOOL EventPipeEventEnabledLoaderCatchCall_V1();
ULONG EventPipeWriteEventLoaderCatchCall_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledLoaderCatchCallEnd();
ULONG EventPipeWriteEventLoaderCatchCallEnd(

);
BOOL EventPipeEventEnabledLoaderCatchCallEnd_V1();
ULONG EventPipeWriteEventLoaderCatchCallEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledFusionInit();
ULONG EventPipeWriteEventFusionInit(

);
BOOL EventPipeEventEnabledFusionInit_V1();
ULONG EventPipeWriteEventFusionInit_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledFusionInitEnd();
ULONG EventPipeWriteEventFusionInitEnd(

);
BOOL EventPipeEventEnabledFusionInitEnd_V1();
ULONG EventPipeWriteEventFusionInitEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledFusionAppCtx();
ULONG EventPipeWriteEventFusionAppCtx(

);
BOOL EventPipeEventEnabledFusionAppCtx_V1();
ULONG EventPipeWriteEventFusionAppCtx_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledFusionAppCtxEnd();
ULONG EventPipeWriteEventFusionAppCtxEnd(

);
BOOL EventPipeEventEnabledFusionAppCtxEnd_V1();
ULONG EventPipeWriteEventFusionAppCtxEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledFusion2EE();
ULONG EventPipeWriteEventFusion2EE(

);
BOOL EventPipeEventEnabledFusion2EE_V1();
ULONG EventPipeWriteEventFusion2EE_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledFusion2EEEnd();
ULONG EventPipeWriteEventFusion2EEEnd(

);
BOOL EventPipeEventEnabledFusion2EEEnd_V1();
ULONG EventPipeWriteEventFusion2EEEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledSecurityCatchCall();
ULONG EventPipeWriteEventSecurityCatchCall(

);
BOOL EventPipeEventEnabledSecurityCatchCall_V1();
ULONG EventPipeWriteEventSecurityCatchCall_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledSecurityCatchCallEnd();
ULONG EventPipeWriteEventSecurityCatchCallEnd(

);
BOOL EventPipeEventEnabledSecurityCatchCallEnd_V1();
ULONG EventPipeWriteEventSecurityCatchCallEnd_V1(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledCLRStackWalkPrivate();
ULONG EventPipeWriteEventCLRStackWalkPrivate(
    const unsigned short  ClrInstanceID,
    const unsigned char  Reserved1,
    const unsigned char  Reserved2,
    const unsigned int  FrameCount,
    const void** Stack
);
BOOL EventPipeEventEnabledModuleRangeLoadPrivate();
ULONG EventPipeWriteEventModuleRangeLoadPrivate(
    const unsigned short  ClrInstanceID,
    const unsigned __int64  ModuleID,
    const unsigned int  RangeBegin,
    const unsigned int  RangeSize,
    const unsigned char  RangeType,
    const unsigned char  IBCType,
    const unsigned short  SectionType
);
BOOL EventPipeEventEnabledBindingPolicyPhaseStart();
ULONG EventPipeWriteEventBindingPolicyPhaseStart(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBindingPolicyPhaseEnd();
ULONG EventPipeWriteEventBindingPolicyPhaseEnd(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBindingNgenPhaseStart();
ULONG EventPipeWriteEventBindingNgenPhaseStart(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBindingNgenPhaseEnd();
ULONG EventPipeWriteEventBindingNgenPhaseEnd(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBindingLookupAndProbingPhaseStart();
ULONG EventPipeWriteEventBindingLookupAndProbingPhaseStart(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBindingLookupAndProbingPhaseEnd();
ULONG EventPipeWriteEventBindingLookupAndProbingPhaseEnd(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledLoaderPhaseStart();
ULONG EventPipeWriteEventLoaderPhaseStart(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledLoaderPhaseEnd();
ULONG EventPipeWriteEventLoaderPhaseEnd(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBindingPhaseStart();
ULONG EventPipeWriteEventBindingPhaseStart(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBindingPhaseEnd();
ULONG EventPipeWriteEventBindingPhaseEnd(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBindingDownloadPhaseStart();
ULONG EventPipeWriteEventBindingDownloadPhaseStart(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBindingDownloadPhaseEnd();
ULONG EventPipeWriteEventBindingDownloadPhaseEnd(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledLoaderAssemblyInitPhaseStart();
ULONG EventPipeWriteEventLoaderAssemblyInitPhaseStart(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledLoaderAssemblyInitPhaseEnd();
ULONG EventPipeWriteEventLoaderAssemblyInitPhaseEnd(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledLoaderMappingPhaseStart();
ULONG EventPipeWriteEventLoaderMappingPhaseStart(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledLoaderMappingPhaseEnd();
ULONG EventPipeWriteEventLoaderMappingPhaseEnd(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledLoaderDeliverEventsPhaseStart();
ULONG EventPipeWriteEventLoaderDeliverEventsPhaseStart(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledLoaderDeliverEventsPhaseEnd();
ULONG EventPipeWriteEventLoaderDeliverEventsPhaseEnd(
    const unsigned int  AppDomainID,
    const unsigned int  LoadContextID,
    const unsigned int  FromLoaderCache,
    const unsigned int  DynamicLoad,
    PCWSTR  AssemblyCodebase,
    PCWSTR  AssemblyName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledEvidenceGenerated();
ULONG EventPipeWriteEventEvidenceGenerated(
    const unsigned int  Type,
    const unsigned int  AppDomain,
    PCWSTR  ILImage,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledModuleTransparencyComputationStart();
ULONG EventPipeWriteEventModuleTransparencyComputationStart(
    PCWSTR  Module,
    const unsigned int  AppDomainID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledModuleTransparencyComputationEnd();
ULONG EventPipeWriteEventModuleTransparencyComputationEnd(
    PCWSTR  Module,
    const unsigned int  AppDomainID,
    const BOOL  IsAllCritical,
    const BOOL  IsAllTransparent,
    const BOOL  IsTreatAsSafe,
    const BOOL  IsOpportunisticallyCritical,
    const unsigned int  SecurityRuleSet,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledTypeTransparencyComputationStart();
ULONG EventPipeWriteEventTypeTransparencyComputationStart(
    PCWSTR  Type,
    PCWSTR  Module,
    const unsigned int  AppDomainID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledTypeTransparencyComputationEnd();
ULONG EventPipeWriteEventTypeTransparencyComputationEnd(
    PCWSTR  Type,
    PCWSTR  Module,
    const unsigned int  AppDomainID,
    const BOOL  IsAllCritical,
    const BOOL  IsAllTransparent,
    const BOOL  IsCritical,
    const BOOL  IsTreatAsSafe,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodTransparencyComputationStart();
ULONG EventPipeWriteEventMethodTransparencyComputationStart(
    PCWSTR  Method,
    PCWSTR  Module,
    const unsigned int  AppDomainID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMethodTransparencyComputationEnd();
ULONG EventPipeWriteEventMethodTransparencyComputationEnd(
    PCWSTR  Method,
    PCWSTR  Module,
    const unsigned int  AppDomainID,
    const BOOL  IsCritical,
    const BOOL  IsTreatAsSafe,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledFieldTransparencyComputationStart();
ULONG EventPipeWriteEventFieldTransparencyComputationStart(
    PCWSTR  Field,
    PCWSTR  Module,
    const unsigned int  AppDomainID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledFieldTransparencyComputationEnd();
ULONG EventPipeWriteEventFieldTransparencyComputationEnd(
    PCWSTR  Field,
    PCWSTR  Module,
    const unsigned int  AppDomainID,
    const BOOL  IsCritical,
    const BOOL  IsTreatAsSafe,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledTokenTransparencyComputationStart();
ULONG EventPipeWriteEventTokenTransparencyComputationStart(
    const unsigned int  Token,
    PCWSTR  Module,
    const unsigned int  AppDomainID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledTokenTransparencyComputationEnd();
ULONG EventPipeWriteEventTokenTransparencyComputationEnd(
    const unsigned int  Token,
    PCWSTR  Module,
    const unsigned int  AppDomainID,
    const BOOL  IsCritical,
    const BOOL  IsTreatAsSafe,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledNgenBindEvent();
ULONG EventPipeWriteEventNgenBindEvent(
    const unsigned short  ClrInstanceID,
    const unsigned __int64  BindingID,
    const unsigned int  ReasonCode,
    PCWSTR  AssemblyName
);
BOOL EventPipeEventEnabledFailFast();
ULONG EventPipeWriteEventFailFast(
    PCWSTR  FailFastUserMessage,
    const void*  FailedEIP,
    const unsigned int  OSExitCode,
    const unsigned int  ClrExitCode,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledPrvFinalizeObject();
ULONG EventPipeWriteEventPrvFinalizeObject(
    const void*  TypeID,
    const void*  ObjectID,
    const unsigned short  ClrInstanceID,
    PCWSTR  TypeName
);
BOOL EventPipeEventEnabledCCWRefCountChange();
ULONG EventPipeWriteEventCCWRefCountChange(
    const void*  HandleID,
    const void*  ObjectID,
    const void*  COMInterfacePointer,
    const unsigned int  NewRefCount,
    const unsigned __int64  AppDomainID,
    LPCSTR  ClassName,
    LPCSTR  NameSpace,
    PCWSTR  Operation,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledPrvSetGCHandle();
ULONG EventPipeWriteEventPrvSetGCHandle(
    const void*  HandleID,
    const void*  ObjectID,
    const unsigned int  Kind,
    const unsigned int  Generation,
    const unsigned __int64  AppDomainID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledPrvDestroyGCHandle();
ULONG EventPipeWriteEventPrvDestroyGCHandle(
    const void*  HandleID,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledFusionMessageEvent();
ULONG EventPipeWriteEventFusionMessageEvent(
    const unsigned short  ClrInstanceID,
    const BOOL  Prepend,
    PCWSTR  Message
);
BOOL EventPipeEventEnabledFusionErrorCodeEvent();
ULONG EventPipeWriteEventFusionErrorCodeEvent(
    const unsigned short  ClrInstanceID,
    const unsigned int  Category,
    const unsigned int  ErrorCode
);
BOOL EventPipeEventEnabledPinPlugAtGCTime();
ULONG EventPipeWriteEventPinPlugAtGCTime(
    const void*  PlugStart,
    const void*  PlugEnd,
    const void*  GapBeforeSize,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledAllocRequest();
ULONG EventPipeWriteEventAllocRequest(
    const void*  LoaderHeapPtr,
    const void*  MemoryAddress,
    const unsigned int  RequestSize,
    const unsigned int  Unused1,
    const unsigned __int64  Unused2,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledMulticoreJit();
ULONG EventPipeWriteEventMulticoreJit(
    const unsigned short  ClrInstanceID,
    PCWSTR  String1,
    PCWSTR  String2,
    const signed int  Int1,
    const signed int  Int2,
    const signed int  Int3
);
BOOL EventPipeEventEnabledMulticoreJitMethodCodeReturned();
ULONG EventPipeWriteEventMulticoreJitMethodCodeReturned(
    const unsigned short  ClrInstanceID,
    const unsigned __int64  ModuleID,
    const unsigned __int64  MethodID
);
BOOL EventPipeEventEnabledIInspectableRuntimeClassName();
ULONG EventPipeWriteEventIInspectableRuntimeClassName(
    PCWSTR  TypeName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledWinRTUnbox();
ULONG EventPipeWriteEventWinRTUnbox(
    PCWSTR  TypeName,
    PCWSTR  SecondTypeName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledCreateRCW();
ULONG EventPipeWriteEventCreateRCW(
    PCWSTR  TypeName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledRCWVariance();
ULONG EventPipeWriteEventRCWVariance(
    PCWSTR  TypeName,
    PCWSTR  InterfaceTypeName,
    PCWSTR  VariantInterfaceTypeName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledRCWIEnumerableCasting();
ULONG EventPipeWriteEventRCWIEnumerableCasting(
    PCWSTR  TypeName,
    PCWSTR  SecondTypeName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledCreateCCW();
ULONG EventPipeWriteEventCreateCCW(
    PCWSTR  TypeName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledCCWVariance();
ULONG EventPipeWriteEventCCWVariance(
    PCWSTR  TypeName,
    PCWSTR  InterfaceTypeName,
    PCWSTR  VariantInterfaceTypeName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledObjectVariantMarshallingToNative();
ULONG EventPipeWriteEventObjectVariantMarshallingToNative(
    PCWSTR  TypeName,
    const signed int  Int1,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGetTypeFromGUID();
ULONG EventPipeWriteEventGetTypeFromGUID(
    PCWSTR  TypeName,
    PCWSTR  SecondTypeName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledGetTypeFromProgID();
ULONG EventPipeWriteEventGetTypeFromProgID(
    PCWSTR  TypeName,
    PCWSTR  SecondTypeName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledConvertToCallbackEtw();
ULONG EventPipeWriteEventConvertToCallbackEtw(
    PCWSTR  TypeName,
    PCWSTR  SecondTypeName,
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledBeginCreateManagedReference();
ULONG EventPipeWriteEventBeginCreateManagedReference(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledEndCreateManagedReference();
ULONG EventPipeWriteEventEndCreateManagedReference(
    const unsigned short  ClrInstanceID
);
BOOL EventPipeEventEnabledObjectVariantMarshallingToManaged();
ULONG EventPipeWriteEventObjectVariantMarshallingToManaged(
    PCWSTR  TypeName,
    const signed int  Int1,
    const unsigned short  ClrInstanceID
);

